### PR TITLE
feat(validated-input): allow setting autocomplete attribute

### LINKED ISSUE #96: Add autocomplete attribute binding
Currently there is no easy way to set the `autocomplete` attribute on a validated-form input.
`autocomplete` makes it easier for users to fill forms as the browser can complete relevant values automatically.

- https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill
- https://cloudfour.com/thinks/autofill-what-web-devs-should-know-but-dont/

If it's ok to add `autocomplete` support to validated-form, I can open a PR later.

### PR DESCRIPTION
**Pull request by makepanic**
fixes #96

### CODE REVIEW

**Comment by anehx** [comment]
Hi @makepanic,

First of all, thank you for opening a PR and contributing to this addon. However, in order to merge this PR we'd like you to add support for an `autocomplete` property on `validated-form`.

If you're interested, you could also add some documentation on how to use this property. Is it a `Boolean` or a `String`, what values does it accept etc.

Let me know if you need help!

**Comment by makepanic** [comment]
Hi,
Thanks for the feedback.
I didn't know that one can also set an autocomplete attribute to the form element.

I'll update the PR soon.

**Comment by makepanic** [comment]
I've updated the PR with some minor documentation and `autocomplete` attribute binding on the form component.

**Comment by czosel** [comment]
:+1: excellent! Thank you :wink:

**Pull request merged**
